### ISSUE TITLE
MBR

### ISSUE THREAD

**Issue by Lashqarashvili** [AzureianGH/AzureOS#1]
[mbr.txt](https://github.com/AzureianGH/AzureOS/files/14084599/mbr.txt)

**Comment by Lashqarashvili** [comment]
You need to change the relocation address in the linker script to 0x2000. I have checked that the code worked on qemu by making a simple 32 bit code which printed a letter on screen. I haven't tested your C code.

**Comment by AzureianGH** [comment]
Hey I really appreciate your file, but unfortunately I just couldn't get it to compile. And right now, my MBR is working correctly. My main issue right now is getting the IDT set up. Thanks for this though!
